### ISSUE TITLE
NEI Crash

### ISSUE THREAD

**Issue by Tkdriverx** [Tkdriverx/TerraFirmaCraft-Additions#1]
The crash seems to only occur when NEI is in recipe mode and you click on a TFC item, causing the internal server to crash.

I believe it may be the NEI TFC plugin that's causing the crash. Looking into it...

**Comment by RandomCayh** [comment]
You can fix this very easily by simply updating TerraFirmaCraft NEI Plugin, my version is 1.7.10-1.5.3.25 and it works fine with the modpack and doesn't crash when you try to check the unique TFC recipes.

**Comment by Tkdriverx** [comment]
The latest version 0.79.28.1 has updated the TFC NEI Plugin.
